### ISSUE TITLE
Breaks validates :uniqueness => true

### ISSUE THREAD

**Issue by the-architect** [norman/friendly_id#152]
my scenario:

a rails app with a user model which uses friendly_id:

``` ruby
# Gemfile:

gem 'rails', '>=3.1.0'
gem "friendly_id", :git => "git://github.com/norman/friendly_id.git"

# app/models/user.rb:

class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false }

  extend FriendlyId
  friendly_id :username, :use => :slugged
end

# factories.rb:

FactoryGirl.define do
  factory :user do
    factory :bob do
      username "Example User"
      email "user@example.com"
      password "foobar"
      password_confirmation "foobar"
    end
  end
end

# spec/models/user_spec.rb

it "should reject duplicate email addresses" do
  user = Factory(:bob)
  Factory.build(:bob).should_not be_valid
end
```

without the lines:

``` ruby
extend FriendlyId
friendly_id :username, :use => :slugged
```

the spec passes. So I figured it might have something to do with friendly_id.

In fact when I run this with friendly_id enabled

``` ruby
User.exists?(:email => 'marcel.scherf@epicteams.com')
```

I get the following error:

``` ruby
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: slug.email: SELECT  1 FROM "users"  WHERE "slug"."email" = 'john.doe@example.com' LIMIT 1
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/sqlite3-1.3.4/lib/sqlite3/database.rb:91:in `initialize'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/sqlite3-1.3.4/lib/sqlite3/database.rb:91:in `new'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/sqlite3-1.3.4/lib/sqlite3/database.rb:91:in `prepare'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/sqlite_adapter.rb:175:in `block in exec_query'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:244:in `block in log'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activesupport-3.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:239:in `log'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/sqlite_adapter.rb:171:in `exec_query'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/sqlite_adapter.rb:382:in `select'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_one'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:30:in `select_value'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/relation/finder_methods.rb:197:in `exists?'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/bundler/gems/friendly_id-c03879ac0227/lib/friendly_id/finder_methods.rb:30:in `exists?'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/activerecord-3.1.0/lib/active_record/base.rb:441:in `exists?'
        from (irb):1
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/railties-3.1.0/lib/rails/commands/console.rb:45:in `start'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/railties-3.1.0/lib/rails/commands/console.rb:8:in `start'
        from /Users/work/.rvm/gems/ruby-1.9.2-p290@project/gems/railties-3.1.0/lib/rails/commands.rb:40:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'>>
```

Is this a known issue or is there an easy way around the problem?

**Comment by vivipoit** [comment]
Hello!

I have `friendly_id 5.1.0` on `Rails 5.1.6` and it seems like it breaks just in terms of case sensitivity.

````ruby
class Event < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :admin

  validates_presence_of :name
  validates_uniqueness_of :name
  
end
````

With this code, I can't create 2 records with `'Test'` as `name`, but I'm able to create `'Test'` and `'test'`.

Any idea if the issue could come back to the gem?

I've tried setting `:case_sensitive => true` explicitly, but that didn't seem to help anything.
