### ISSUE TITLE
friendly_id Error when migrating with history plugin

### ISSUE THREAD

**Issue by malomalo** [norman/friendly_id#299]
I get the following when Trying to call any model or reseting the column information on a model:

``` shell
==  AddCounterCachesToAddresses: migrating ====================================
rake aborted!
An error has occurred, this and all later migrations canceled:

PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block
: SELECT  "addresses".* FROM "addresses"  LIMIT 1
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:1151:in `async_exec'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:1151:in `exec_no_cache'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:664:in `block in exec_query'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activesupport-3.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:663:in `exec_query'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:1246:in `select'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/querying.rb:38:in `block in find_by_sql'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/explain.rb:40:in `logging_query_plan'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/querying.rb:37:in `find_by_sql'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/relation.rb:171:in `exec_queries'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/relation.rb:160:in `block in to_a'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/explain.rb:40:in `logging_query_plan'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/relation.rb:159:in `to_a'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/relation/finder_methods.rb:376:in `find_first'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/relation/finder_methods.rb:122:in `first'
/usr/local/Cellar/ruby/1.9.3-p194/lib/ruby/gems/1.9.1/gems/activerecord-3.2.5/lib/active_record/querying.rb:5:in `first'
/Users/jon/code/mls/db/migrate/20120611220614_add_counter_caches_to_addresses.rb:3:in `change'
```

I've narrowed it down to when the history plugin is used. The logs show the following query that errors in Postgres:

``` shell
PG::Error: ERROR:  relation "slugs" does not exist
LINE 4:              WHERE a.attrelid = '"slugs"'::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"slugs"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum

  Address Load (1.1ms)  SELECT "addresses".* FROM "addresses" LIMIT 1
PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block
: SELECT  "addresses".* FROM "addresses"  LIMIT 1
   (0.1ms)  ROLLBACK
Connecting to database specified by database.yml
```

Been trying all day to get to the bottom of this, but no success yet.

**Comment by abdulhanan001** [comment]
I am having the same issues
Can anyone tell me what should I do 
using rails 5.0.3
