### ISSUE TITLE
use: :finders breaks rake db:schema:load when working with STI

### ISSUE THREAD

**Issue by pluff** [norman/friendly_id#573]
As noticed here: http://norman.github.io/friendly_id/file.Guide.html#Setting_Up_FriendlyId_in_Your_Model
I have to extend my every STI model to use FriendlyId model. However this breaks rake tasks if there is no schema loaded in DB.
Here is callstack:

```
rake db:create db:schema:load
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 5:                WHERE a.attrelid = '"users"'::regclass
^
    :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                           pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
FROM pg_attribute a LEFT JOIN pg_attrdef d
ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attrelid = '"users"'::regclass
AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `async_exec'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `block in exec_no_cache'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
.../gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:815:in `exec_no_cache'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:969:in `column_definitions'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:187:in `columns'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:93:in `block in prepare_default_proc'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:44:in `yield'
.../gems/activerecord-4.1.1/lib/active_record/connection_adapters/schema_cache.rb:44:in `columns'
.../gems/activerecord-4.1.1/lib/active_record/model_schema.rb:214:in `columns'
.../gems/activerecord-4.1.1/lib/active_record/model_schema.rb:223:in `columns_hash'
.../gems/activerecord-4.1.1/lib/active_record/inheritance.rb:42:in `descends_from_active_record?'
.../gems/activerecord-4.1.1/lib/active_record/inheritance.rb:48:in `finder_needs_type_condition?'
.../gems/activerecord-4.1.1/lib/active_record/core.rb:169:in `relation'
.../gems/friendly_id-5.0.4/lib/friendly_id/finders.rb:78:in `block in setup'
.../gems/friendly_id-5.0.4/lib/friendly_id/finders.rb:77:in `instance_eval'
.../gems/friendly_id-5.0.4/lib/friendly_id/finders.rb:77:in `setup'
.../gems/friendly_id-5.0.4/lib/friendly_id/configuration.rb:48:in `block in use'
.../gems/friendly_id-5.0.4/lib/friendly_id/configuration.rb:46:in `map'
.../gems/friendly_id-5.0.4/lib/friendly_id/configuration.rb:46:in `use'
.../gems/friendly_id-5.0.4/lib/friendly_id/base.rb:193:in `friendly_id'
.../app/models/owner.rb:5:in `<class:Owner>'
```

the code:

``` ruby
class Owner < User

  extend FriendlyId
  friendly_id :full_name, use: [:slugged, :finders]
end
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :full_name, use: [:slugged, :finders]
end
```

Without finders everything works fine.

**Comment by bessey** [comment]
@malroc did you ever get to the bottom of it? I have exactly the same problem, and wondered if we could compare gemfile.lock's for a common potential source:
https://gist.github.com/bessey/535439b028d6f07bf760e253b19ffdbf

**Comment by malroc** [comment]
@bessey I think I just decided to somehow workaround the issue, but that was long ago, and I don't remember the details
