### ISSUE TITLE
sequentially_slugged raises error when attribute value doesn't exist

### ISSUE THREAD

**Issue by joker-777** [norman/friendly_id#732]
Hello,

we create a slug of a name attribute with the `sequentially_slugged` module and it raises an error when the value doesn't exist. It happens before the `presence` validation takes place.
```
NoMethodError - undefined method `+' for nil:NilClass:
  friendly_id (5.2.0.beta.1) lib/friendly_id/sequentially_slugged.rb:29:in `next_slug'
  friendly_id (5.2.0.beta.1) lib/friendly_id/sequentially_slugged.rb:15:in `resolve_friendly_id_conflict'
  friendly_id (5.2.0.beta.1) lib/friendly_id/slugged.rb:309:in `set_slug'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
  activemodel (4.2.5.1) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
  activemodel (4.2.5.1) lib/active_model/validations.rb:338:in `valid?'
  activerecord (4.2.5.1) lib/active_record/validations.rb:58:in `valid?'
  activerecord (4.2.5.1) lib/active_record/validations.rb:83:in `perform_validations'
  activerecord (4.2.5.1) lib/active_record/validations.rb:37:in `save'
  activerecord (4.2.5.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:286:in `block in save'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  activerecord (4.2.5.1) lib/active_record/transactions.rb:285:in `save'
```

**Comment by kimrgrey** [comment]
@joker-777, hi! Could you please provide some code of the model for which it happens? Are you using master version of the gem?

**Comment by joker-777** [comment]
This was fixed by https://github.com/norman/friendly_id/pull/720
