### ISSUE TITLE
Multiple model creation with slug on same field fails

### ISSUE THREAD

**Issue by mindseyeblind** [norman/friendly_id#780]
I am running a Rails 5 application which has 2 models - a `User` and a `Provider`. I am using multiple table inheritance to show that each `Provider` "is a" `User` (via the [active_record-acts_as](https://github.com/hzamani/active_record-acts_as) gem). So, in effect, creating a `Provider` with the related fields would create a `User` at the same time.

Both models are slugged via a field called `username`. The code in question being:
```
class User
  extend FriendlyId
  friendly_id :username, use: :slugged
  # ...
end
```

for the `User` model and

```
class Provider
  extend FriendlyId
  friendly_id username, use: :slugged

  def username
    acting_as.username # this fetches the parent model (User)'s `username` field.
  end
  # ...
end
```

for the `Provider` model.

When I attempt to create a `Provider` via a controller action (`providers#create`), it fails, with the error being:

```
TypeError at /providers
nil is not a symbol nor a string
```

The stack trace identifies the problem to be at `lib/friendly_id/slugged.rb:299`, which is the body of the `should_generate_new_friendly_id?` method. This method was called by the `set_slug` method in the same file, `slugged.rb`.

The request parameters were:
```
{ "utf8"=>"✓",
  "authenticity_token"=>"Vws57fdZ8kcKwRz6cRWffKze34O4P4wzlmAGpJkigUFT4TCJ/hByqu0huhz5qbcD80EV1f+tJkYWYRTDpuFy7w==",
  "provider"=>{
    "email"=>"a@a.com",
    "name"=>"A",
    "username"=>"thisuser",
    "password"=>"[FILTERED]",
    "password_confirmation"=>"[FILTERED]",
    "service"=>"Rental"
  },
  "commit"=>"Register as Provider"
}
```

The full stack trace is as follows:

```
TypeError - (╯°□°）╯︵ ┻━┻ : nil is not a symbol nor a string:
  friendly_id (5.1.0) lib/friendly_id/slugged.rb:295:in `should_generate_new_friendly_id?'
  friendly_id (5.1.0) lib/friendly_id/slugged.rb:304:in `set_slug'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:770:in `block (2 levels) in deprecated_false_terminator'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:769:in `block in deprecated_false_terminator'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
  activemodel (5.0.0.1) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
  activemodel (5.0.0.1) lib/active_model/validations.rb:338:in `valid?'
  activerecord (5.0.0.1) lib/active_record/validations.rb:65:in `valid?'
  activerecord (5.0.0.1) lib/active_record/validations.rb:82:in `perform_validations'
  activerecord (5.0.0.1) lib/active_record/validations.rb:44:in `save'
  activerecord (5.0.0.1) lib/active_record/attribute_methods/dirty.rb:22:in `save'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:319:in `block (2 levels) in save'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
  activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
  activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
  activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:211:in `transaction'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:319:in `block in save'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
  activerecord (5.0.0.1) lib/active_record/transactions.rb:318:in `save'
  activerecord (5.0.0.1) lib/active_record/suppressor.rb:41:in `save'
  app/controllers/artists_controller.rb:35:in `block in create'
  actionpack (5.0.0.1) lib/action_controller/metal/mime_responds.rb:195:in `respond_to'
  app/controllers/artists_controller.rb:34:in `create'
  actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
  actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by AhmedNadar** [comment]
I have the same issue here. When I try run `db:seed` to populate categories,  I got `TypeError: ForumThread(id: integer, subject: string, user_id: integer, created_at: datetime, updated_at: datetime, category_id: integer, slug: string, pinned: boolean, locked: boolean, hidden: boolean) is not a symbol nor a string`.

Any solution?!
