### ISSUE TITLE
Error when setting up friendly_id with PostgreSQL ('pg' gem)

### ISSUE THREAD

**Issue by haydennyyy** [norman/friendly_id#784]
Hello all,

I can't get FriendlyId working with the `pg` gem. Here is my output when running `rails g friendly_id`:
```
/home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': Could not load 'active_record/connection_adapters/postqresql_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_handling.rb:53:in `establish_connection'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/railtie.rb:125:in `block (2 levels) in <class:Railtie>'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:33:in `block in on_load'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:32:in `each'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:32:in `on_load'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activerecord-5.0.1/lib/active_record/railtie.rb:121:in `block in <class:Railtie>'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
	from /media/hayden/PROJECTS/portfolio/config/environment.rb:5:in `<top (required)>'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/hayden/.linuxbrew/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```
Of which, this jumps out at me:
```/home/hayden/.linuxbrew/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': Could not load 'active_record/connection_adapters/postqresql_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)```

This might help too.
```ruby
# Gemfile
source 'https://rubygems.org'

gem 'rails', '~> 5.0.1'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'pygments.rb', '~> 0.6.0'
gem 'redcarpet', '~> 3.2.2'
gem 'friendly_id'
gem 'pg'
gem 'web-console', '>= 3.3.0'
gem 'listen', '~> 3.0.5'
gem 'spring'
gem 'spring-watcher-listen', '~> 2.0.0'
gem 'byebug', platform: :mri
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```
The only reason I am not using SQLite3 is because I wish to deploy to Heroku. Unless anybody knows of a better deployment service that's free, or a way to get Rails working with Firebase.

If you could help me, that would be great. The friendlyId feature isn't integral, but it would make my site run a lot better.

**Comment by hajder** [comment]
This is not FriendlyId problem, you should head over to StackOverflow and search there. My wild guess is you didn't `bundle install` or restart the console/server.

**Comment by haydenbjyoung** [comment]
Fair enough, thanks :)
