### ISSUE TITLE
[Rails 5.1] wrong argument type Class (expected Module)

### ISSUE THREAD

**Issue by hron84** [norman/friendly_id#842]
I just installed FriendlyID as described in README. I did not touched any config and I just added the AR versio number to the migration - again, as it is described in the README.

```ruby
# app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slug
end
```
And after ran all migrations, I tried to create a new Article and I get this:
```
[1] pry(main)> a=Article.new
TypeError: wrong argument type Class (expected Module)
from /home/hron/.rvm/gems/ruby-2.4.1@dhportal/gems/friendly_id-5.2.3/lib/friendly_id/configuration.rb:56:in `include'
[2] pry(main)> wtf
Exception: TypeError: wrong argument type Class (expected Module)
--
0: /home/hron/.rvm/gems/ruby-2.4.1@dhportal/gems/friendly_id-5.2.3/lib/friendly_id/configuration.rb:56:in `include'
1: /home/hron/.rvm/gems/ruby-2.4.1@dhportal/gems/friendly_id-5.2.3/lib/friendly_id/configuration.rb:56:in `block in use'
2: /home/hron/.rvm/gems/ruby-2.4.1@dhportal/gems/friendly_id-5.2.3/lib/friendly_id/configuration.rb:53:in `map'
3: /home/hron/.rvm/gems/ruby-2.4.1@dhportal/gems/friendly_id-5.2.3/lib/friendly_id/configuration.rb:53:in `use'
4: /home/hron/.rvm/gems/ruby-2.4.1@dhportal/gems/friendly_id-5.2.3/lib/friendly_id/base.rb:209:in `friendly_id'
```
About:

```
About your application's environment
Rails version             5.1.4
Ruby version              2.4.1-p111 (x86_64-linux)
RubyGems version          2.6.11
Rack version              2.0.3
JavaScript Runtime        Node.js (V8)
Middleware                Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, MetaRequest::Middlewares::Headers, WebConsole::Middleware, ActionDispatch::DebugExceptions, Rollbar::Middleware::Rails::RollbarMiddleware, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, Rack::Head, Rack::ConditionalGet, Rack::ETag, MetaRequest::Middlewares::MetaRequestHandler, MetaRequest::Middlewares::AppRequestHandler
Application root          /home/hron/Projects/job/dragonhall/dhportal
Environment               development
Database adapter          mysql2
Database schema version   20171024135359
```

**Comment by parndt** [comment]
Can you try swapping use: :slug for use: :slugged ?

**Comment by hron84** [comment]
Yeah, it solved the problem, thanks. I thought it is the column name, not a plugin name. Suggestion: make the key is more descriptive, like `plugins:`

**Comment by parndt** [comment]
Thank you for confirming and for the suggestion 👍
