### ISSUE TITLE
StandardError: An error has occurred, this and all later migrations canceled

### ISSUE THREAD

**Issue by Sumeet-Raina** [norman/friendly_id#956]
Using ruby 2.6.3
Rails 6.0.3.3
gem 'friendly_id', '~> 5.1.0'
Error was raised while running `db:migrate`
-----------------------------------------------------------------------------------------------------------------------------
Sumeets-MacBook-Air:SumeetRaina sumeetraina$ rails db:migrate
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFriendlyIdSlugs < ActiveRecord::Migration[4.2]
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:536:in `inherited'
/Users/sumeetraina/Desktop/SumeetRaina/db/migrate/20201005064722_create_friendly_id_slugs.rb:1:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Library/Ruby/Gems/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1010:in `load_migration'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1006:in `migration'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1002:in `disable_ddl_transaction'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1368:in `use_transaction?'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1360:in `ddl_transaction'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1280:in `each'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1229:in `block in migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1229:in `migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1061:in `up'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1036:in `migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:84:in `each'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/command.rb:48:in `invoke'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/Users/sumeetraina/Desktop/SumeetRaina/bin/rails:9:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/sumeetraina/Desktop/SumeetRaina/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFriendlyIdSlugs < ActiveRecord::Migration[4.2]
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:536:in `inherited'
/Users/sumeetraina/Desktop/SumeetRaina/db/migrate/20201005064722_create_friendly_id_slugs.rb:1:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Library/Ruby/Gems/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1010:in `load_migration'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1006:in `migration'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1002:in `disable_ddl_transaction'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1368:in `use_transaction?'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1360:in `ddl_transaction'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1280:in `each'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1229:in `block in migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1229:in `migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1061:in `up'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1036:in `migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:84:in `each'
/Library/Ruby/Gems/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/command.rb:48:in `invoke'
/Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
/Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
/Users/sumeetraina/Desktop/SumeetRaina/bin/rails:9:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Library/Ruby/Gems/2.6.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/sumeetraina/Desktop/SumeetRaina/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by Sumeet-Raina** [comment]
I have solved this issue now, By updating the Gem to '5.4.0' and deleting the table schema, migration file, and initializer. 
Then I ran into this issue 
`Caused by:
PG::DuplicateTable: ERROR:  relation "friendly_id_slugs" already exists`
which was resolved by using `rails db:reset`
