### ISSUE TITLE
[regression] Cannot use slug_candidates symbols

### ISSUE THREAD

**Issue by matthee** [norman/friendly_id#961]
I'm struggling to define friendly ids using the `slug_candidates` method. Saving a record always leads to an ArgumentError.

```
ArgumentError (wrong number of arguments (given 1, expected 0))
```

My definition basically looks like this:

```ruby
class MyModel < ApplicationRecord
  belongs_to :user 
  include FriendlyId
  
  friendly_id :slug_candidates, use: [:slugged]
  
  def slug_candidates
     [:title, [:title, :creator_name]]
  end

  def creator_name
    user.name
  end  
end
```

The controller implementation is pretty basic as well:

```ruby
class MyModelsController 
  # [...]
  def create
    @my_model = MyModel.new(my_model_params)
    @my_model.user = current_user
    
    if @my_model.save 
      redirect_to @my_model
    else
      render :new
    end
  end

  private
  def my_model_params
    params.require(:my_model).permit(:title)
  end
end
```

Snipped Backtrace: 
```
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/attribute_methods/read.rb:15:in `method'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/candidates.rb:51:in `block in to_candidate_array'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/candidates.rb:44:in `map'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/candidates.rb:44:in `to_candidate_array'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/candidates.rb:13:in `initialize'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/slugged.rb:357:in `new'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/slugged.rb:357:in `set_slug'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/friendly_id-5.4.1/lib/friendly_id/slugged.rb:357:in `set_slug'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `catch'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:201:in `block in halting'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `each'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.3.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activemodel-6.0.3.4/lib/active_model/validations.rb:337:in `valid?'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:68:in `valid?'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:84:in `perform_validations'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:47:in `save'
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `block in save'
```

This error can be circumvented by defining the `slug_candidates` method to use lambdas:

```ruby
def slug_candidates
  [
    -> { title },
    -> { [title, creator_name] }
  ]
end
```

## Expected Result

Saving the model *just works* ™️

## Actual Result

During saving an exception is thrown

## Setup
Ruby Version: 2.6.5p114
Rails Version: 6.0.3.4
Friendly Id: 5.4.1

**Comment by rromanchuk** [comment]
+1
